name: Create JIRA Issue
on:
  issues:
    types: [opened]
jobs:
  jira:
    name: Create an Issue in Jira with the GitHub issue information
    runs-on: ubuntu-latest
    env:
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      API_KEY: ${{ secrets.JIRA_API_KEY }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_PROJECT_ID: ${{ secrets.JIRA_PROJECT_ID }}
      JIRA_REPORTER: ${{ secrets.JIRA_REPORTER }}
      JIRA_EPIC_ID: ${{ secrets.EPIC_ID }}
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Save Issue Information
        id: issue-info
        run: |
         summary="${{ github.event.issue.title }}"
         if [[ $summary == *"'"* ]]; then
            summary=$(echo "${summary//\'/''}")
         fi

         description="${{ github.event.issue.body }}"
         if [[ $description == *"'"* ]]; then
            description=$(echo "${description//\'/''}")
         fi

         echo "::set-output name=summary::${summary}"
         echo "::set-output name=description::${description}"
      - name: Create a similar Issue in JIRA
        run: |
          result=$(curl --request POST \
            --url '${{ env.JIRA_URL }}' \
            --user '${{ env.JIRA_USER_EMAIL }}:${{ env.API_KEY }}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data '
              {
                "fields": {
              		"project": {
                    "key": "${{ env.JIRA_PROJECT_ID }}"
                  },
              		"issuetype": {
                    "name": "Bug"
                  },
                  "summary": "${{ steps.issue-info.outputs.summary }}",
                  "description": "[Automated opening comment]: ${{ steps.issue-info.outputs.description }}",
                  "reporter": {
                    "id": "${{ env.JIRA_REPORTER }}"
                  },
              		"priority": {
              			"name": "Medium"
              		},
                  "labels": [
                    "bugfix",
                    "github_created_issue"
                  ],
                  "customfield_10014": "${{ env.JIRA_EPIC_ID }}"
                }
              }
            ')
          issueID=$(echo $result | jq '.id')
          if [ -z "issueID" ]; then
            echo $result
            echo "The workflow has failed."
            exit 1
          else
            echo "Issue created successfully."
            echo "Issue ID is ${issueID}"
          fi
