name: omic_learn
channels:
  - defaults
dependencies:
  - python=3.7
  - py-xgboost=1.3.3
  - pip=21.1.3
  - pip:
      - streamlit==0.84.1
      - pandas==1.2.4
      - numpy==1.21.0
      - scikit-learn==0.24.2
      - openpyxl==3.0.7
      - plotly==5.1.0
      - kaleido==0.2.1
      - XlsxWriter==1.4.0
      - watchdog==2.1.3
